.TH gr1c "1"
.SH NAME
gr1c \- a software suite for GR(1) synthesis and related activities
.SH SYNOPSIS
.B gr1c
.RB [\| \-vlspriP ]\|
.RB [\| \-n
.IR INIT ]\|
.RB [\| \-t
.IR TYPE ]\|
.RB [\| \-o
.IR FILE ]\|
.RI [\| FILE ]\|
.br
.B gr1c
.I COMMAND
.R "[\|...]\|"
.br
.B gr1c
.RB [\| \-hV ]\|
.SH DESCRIPTION
.B gr1c
is a collection of tools for GR(1) synthesis and related activities.  Its core
functionality is checking realizability of and synthesizing strategies for GR(1)
specifications, though it does much more.

The citable URL is http://scottman.net/2012/gr1c
